### ISSUE TITLE
https://directory.libraries.fi/search shows some UI texts in Swedish instead of English

### ISSUE THREAD

**Issue by olli-suutari-jkl** [libraries-fi/kirjastohakemisto#2]
https://directory.libraries.fi/search shows some UI texts in Swedish instead of English

Eq. 
![image](https://user-images.githubusercontent.com/42733913/45955159-d54a5780-c017-11e8-9ad8-57db89926593.png)

**Comment by sjuvonen** [comment]
Thanks for the report.
Fixed in b174c2672fbcf2ab3859becc6b9bfa8bd102e21f.
